theme = "base16_transparent"

[editor]
line-number = "relative"
auto-completion = true
completion-timeout = 5
preview-completion-insert = true
bufferline = "multiple"
popup-border = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert.j]
k = "normal_mode"

[keys.normal.g]
a = "code_action"
